name: Secret Scan

on:
  pull_request:
  push:
    branches: [ master, main ]

jobs:
  trufflehog-scan:
    name: TruffleHog secret scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run TruffleHog scan
        uses: trufflesecurity/trufflehog-action@v2
        with:
          scan_type: 'git'
          # fail the job if findings are present
          exit_on_secrets: 'true'
